language: node_js
node_js:
  - 6
  - 8
  - node

matrix:
  allow_failures:
  - node_js: node

script:
  - npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && cat ./coverage/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js
