pipelines:
  pugin-components:
    group: Dependencies
    label_template: "${COUNT}"
    materials:
      pugin-components-git:
        git: https://github.com/ukparliament/pugin-components.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          approval: manual
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - checkout_to_release
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release

environments:
  Web.LIVE:
    pipelines:
      - pugin-components